sudo: required
dist: trusty
language: node_js
node_js:
  - "7"
cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules
branches:
  only:
    - master
    - /.*/
before_install:
 # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add @angular/cli
  - yarn global add firebase-tools
  - yarn global add gulp-cli
install:
  - yarn install
script:
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
